### ISSUE TITLE
请问这里（infer_thresh) 和 (down_stride）的意义是什么呢？有什么调整技巧？

### ISSUE THREAD

**Issue by DongLizhong** [CaoWGG/TensorRT-YOLOv4#13]

**Comment by CaoWGG** [comment]
@DongLizhong 
您好，infer_thresh 是指推理是预测框置信度的阈值。低于这个值的预测框将会忽略。
down_stride是yolo层所输入的feature map相对输入图像的下采样倍数。
比如当输入是416x416时，13x13的feature map对应的down_stride = 32 (416/13)

**Comment by DongLizhong** [comment]
> @DongLizhong
> 您好，infer_thresh 是指推理是预测框置信度的阈值。低于这个值的预测框将会忽略。
> down_stride是yolo层所输入的feature map相对输入图像的下采样倍数。
> 比如当输入是416x416时，13x13的feature map对应的down_stride = 32 (416/13)

**Comment by DongLizhong** [comment]
感谢回答，请问这里如果我调整了网络的输出为104×104、52×52、和26×26；那我是不是down_stride为4、8、16就可以了呢？我试了一下，没有输出。

**Comment by CaoWGG** [comment]
@DongLizhong
网络结构固定了，down_stride就固定了
对于YOLOv3，或者YOLOv4，输出的特征图分别是下采样32,16,8倍.
当输入是832x832时，输出分别是 26x26, 52x52, 104x104
