### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by fqlovetb** [CaoWGG/TensorRT-YOLOv4#14]
您好，我用的是tensorRT7.0版本，make的时候出现了这个问题，请问这个问题是啥？是tensorRT版本问题吗？
![Screenshot from 2020-05-26 16-50-55](https://user-images.githubusercontent.com/34056884/82881710-9f8b0e00-9f72-11ea-947a-eddeebadc493.png)

**Comment by CaoWGG** [comment]
@fqlovetb
您好，TensorRT 7 肯定是不能跑的, TensorRT7变化太大了。
您可以试试TensorRT 6, TensorRT 6 经网友测试说是可以跑的。

**Comment by fqlovetb** [comment]
好的，我这刷机就是7.我在瞅瞅
