### ISSUE TITLE
大佬，TensorRT7的可以放出来吗？

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [CaoWGG/TensorRT-YOLOv4#23]
因为NX 上TensorRT的版本只有7，所以能不能放出来呀！自己做的，动态shape那里不是很明白 ，加了个explicit batch最后没出来结果

**Comment by CaoWGG** [comment]
@CallmeZhangChenchen 
最近比较忙，还没上传。
tensorrt7也是固定shape的，没有实现动态shape的(之前实现过，速度太慢了)

**Comment by HappyKerry** [comment]
@CaoWGG @CallmeZhangChenchen NX上是TensorRT 7.1，nvidia都没这个PC版本下载……

**Comment by CaoWGG** [comment]
@HappyKerry 
NX 香吗？

**Comment by HappyKerry** [comment]
> @HappyKerry
> NX 香吗？
香是香，就是trt7.1烦人

**Comment by CallmeZhangChenchen** [comment]
@CaoWGG @HappyKerry   trt7  感觉 固定shape  对 onnx模型的使用方式也变了  ，   我转换过模型之后  出来的结果不对了    很玄乎  不知道内部改了什么东西

**Comment by CallmeZhangChenchen** [comment]
@CaoWGG     谢谢你的回复， 请问 tensorrt7上面 你测试结果是否是正确的呢

**Comment by HappyKerry** [comment]
@CallmeZhangChenchen 7.0的结果是正确的，7.1的不行，nx是7.1

**Comment by CallmeZhangChenchen** [comment]
HI  @ @ @HappyKerry      现在PC端有7.1了啦！
