### ISSUE TITLE
关于No plugin registered for op

### ISSUE THREAD

**Issue by Stephenfang51** [CaoWGG/TensorRT-YOLOv4#33]
您好

近期测试您的项目是没问题的， 

但是将项目下编译好的库文件 libmynvonnx...etc 拉到我自己的项目下

并且另外写了个inference函数（均模仿runDet的写法）， 在调用这个函数的时候

会出现No plugin registered for op : FancyActivation
还有No plugin registered for op : Yolo 这些

是不是不能直接这样移植编译好的库文件？

**Comment by CaoWGG** [comment]
@Stephenfang51
可以在生成库的时候前面的 my 去掉试试
在onnx-tensorrt/CMakeFilelist.txt

**Comment by Stephenfang51** [comment]
> @Stephenfang51
> 可以在生成库的时候前面的 my 去掉试试
> 在onnx-tensorrt/CMakeFilelist.txt

您好 謝謝您快速回應
我試過以下方法， 直接将生成的libmyonnxparser.so 跟libmyonnxparser_runtime 替换掉TensorRT 中同名的库， 但是这样依然报错同样找不到op的错， 而找不到的错op就是onnx-tensorrt中自定义的

另外也试了您的方法 其实跟我第一个方法是换汤不换药的样子， 所以依然没有用
不晓得您这边有没有什么见解， 随意给点都好 我是想不出来了....

顺道一提 我的函数并没有用cmake 将函数与 libmynvonnxparser等库进行链接， 因为项目是qt， 会不会是这个原因

**Comment by CaoWGG** [comment]
@Stephenfang51 
https://github.com/CaoWGG/TensorRT-YOLOv4/blob/4d7c2edce99e8794a4cb4ea3540d51ce91158a36/src/trt.cpp#L150
还要注意解析模型 和生成模型的时候需要将pluginfactoy 传入进去(tensorrt <= 5)
对于tensorrt>=6  有一个 initnv...plugin 的方法，来初始化plugin

**Comment by Stephenfang51** [comment]
> @Stephenfang51
> https://github.com/CaoWGG/TensorRT-YOLOv4/blob/4d7c2edce99e8794a4cb4ea3540d51ce91158a36/src/trt.cpp#L150
> 
> 
> 还要注意解析模型 和生成模型的时候需要将pluginfactoy 传入进去(tensorrt <= 5)
> 对于tensorrt>=6 有一个 initnv...plugin 的方法，来初始化plugin

是的 这边都用上了 基本和您的代码是一致的
报错的地方在下一句
`mEngine = shared_ptr<nvinfer1::ICudaEngine>(mRunTime->deserializeCudaEngine(data.get(), length, mPlugin),InferDeleter());`

至于您说的trt >=6， initnv plugin方法是指什么呢？
因为我也是直接用的trt6.0.1.5 来跑您的项目的， 一点问题也没有的！

**Comment by Stephenfang51** [comment]
如果我将我需要的API写在您的项目中， 并将您整个项目编译成一个库， 然后在我的项目中来调用， 您认为这个方式是否可行呢？
