### ISSUE TITLE
TensorRT 7 support

### ISSUE THREAD

**Issue by lovexytoo** [CaoWGG/TensorRT-YOLOv4#4]
Is there a plan that your TensorRT series projects upgrade to support TensorRT 7 ?

**Comment by CaoWGG** [comment]
@lovexytoo 
I have implemented YOLOV4 with tensorrt 7 dynamic shape. But the speed is much slower than tensorrt 5 fixed shape.

**Comment by lovexytoo** [comment]
@CaoWGG 
Thanks for the reply. How about fix shape but dynamic batch size? TensorRT 7 support adding multiple optimization profiles for dynamic batch size inference. In official document, the performance is even better than explicit batch size.
