### ISSUE TITLE
失败：尝试在TensorRT-YOLOv4/onnx-tensorrt/下生成onnx2trt可执行文件进行转换 

### ISSUE THREAD

**Issue by jch-wang** [CaoWGG/TensorRT-YOLOv4#49]
转换到.onnx成功，但生成.engine失败，运行如下:
```
$./buildEngine -i model/yolov4.onnx -o model/yolov4.engine -b 1 -m 0
input-onnx: model/yolov4.onnx
output-engine: model/yolov4.engine
max-batchsize: 1
calib-file: 
----------------------------------------------------------------
Input filename:   model/yolov4.onnx
ONNX IR version:  0.0.4
Opset version:    9
Producer name:    https://github.com/CaoWGG
Producer version: 
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Begin building engine...
End building engine...
Killed
```

以下是我的jetson nano配置：
JetPack4.4； cuDNN 8.0； CUDA 10.2； OpenCV 4.1.1； Visionworks 1.6； python3 3.6.9； TensorRT 7.1.3.4

随后我尝试生成.trt文件:  在TensorRT-YOLOv4/onnx-tensorrt/目录下
```
mkdir build
cd build
cmake .. -DTENSORRT_ROOT=/opt/tensorrt -DGPU_ARCHS="53"
make 
sudo make install
```
但是没有发现生成onnx2trt的可执行文件。

**Comment by CallmeZhangChenchen** [comment]
你可以看看这个  
https://github.com/CaoWGG/TensorRT-YOLOv4/issues/23

**Comment by jch-wang** [comment]
> 你可以看看这个
> #23

兄弟，我转换成功了，是转换中nano的memory资源紧张问题，把FP32换为FP16就🆗了，若和我的nano配置相同可以参考hlld对CaoWGG修改后的代码。
github：https://github.com/hlld/tensorrt-yolov4
CSDN：https://blog.csdn.net/hlld__/article/details/107551084#comments_13332515

**Comment by jch-wang** [comment]
> 你可以看看这个
> [＃23](https://github.com/CaoWGG/TensorRT-YOLOv4/issues/23)

我现在更想知道在TensorRT-YOLOv4/ onnx-tensorrt /提到的使用onnx2trt可执行文件的转换方法，没有尝试成功~~

**Comment by CallmeZhangChenchen** [comment]
@jch-wang   好的   多谢分享  
可能TensorRT-YOLOv4  专门对 onnx-tensorrt 做过什么修改  我也不知道哈  只是猜测
